steps:
  - name: "gcr.io/cloud-builders/docker"
    args: [
        "build",
        # '--no-cache' IS DELETED FROM RIGHT HERE!
        "-t",
        "us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/double-checkk-api:$COMMIT_SHA",
        "-f",
        "CloudRun/Dockerfile",
        "CloudRun",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/double-checkk-api:$COMMIT_SHA",
      ]

images:
  - "us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/double-checkk-api:$COMMIT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY
